--Table Creation


CREATE TABLE STG_CHURN (
	CUSTOMER_ID VARCHAR NOT NULL PRIMARY KEY,
	GENDER VARCHAR,
	AGE INT,
	MARRIED VARCHAR,
	STATE VARCHAR,
	NUMBER_OF_REFERRALS INT,
	TENURE_IN_MONTHS INT,
	VALUE_DEAL VARCHAR,
	PHONE_SERVICE VARCHAR,
	MULTIPLE_LINES VARCHAR,
	INTERNET_SERVICE VARCHAR,
	INTERNET_TYPE VARCHAR,
	ONLINE_SECURITY VARCHAR,
	ONLINE_BACKUP VARCHAR,
	DEVICE_PROTECTION_PLAN VARCHAR,
	PREMIUM_SUPPORT VARCHAR,
	STREAMING_TV VARCHAR,
	STREAMING_MOVIES VARCHAR,
	STREAMING_MUSIC VARCHAR,
	UNLIMITED_DATA VARCHAR,
	CONTRACT VARCHAR,
	PAPERLESS_BILLING VARCHAR,
	PAYMENT_METHOD VARCHAR,
	MONTHLY_CHARGE FLOAT,
	TOTAL_CHARGES FLOAT,
	TOTAL_REFUNDS FLOAT,
	TOTAL_EXTRA_DATA_CHARGES FLOAT,
	TOTAL_LONG_DISTANCE_CHARGES FLOAT,
	TOTAL_REVENUE FLOAT,
	CUSTOMER_STATUS VARCHAR,
	CHURN_CATEGORY VARCHAR,
	CHURN_REASON VARCHAR
);
SELECT
	*
FROM
	STG_CHURN
LIMIT
	10;

--Data Exploration – Check Distinct Values

SELECT
	GENDER,
	COUNT(GENDER) AS TOTALCOUNT,
	ROUND(
		COUNT(GENDER) * 1.0 / (
			SELECT
				COUNT(*)
			FROM
				STG_CHURN
		),
		2
	) AS PERCENTAGE
FROM
	STG_CHURN
GROUP BY
	GENDER;


SELECT
	CONTRACT,
	COUNT(CONTRACT) AS TOTALCOUNT,
	ROUND(
		COUNT(CONTRACT) * 1.0 / (
			SELECT
				COUNT(*)
			FROM
				STG_CHURN
		),
		2
	) AS PERCENTAGE
FROM
	STG_CHURN
GROUP BY
	CONTRACT;


SELECT
	CUSTOMER_STATUS,
	COUNT(CUSTOMER_STATUS) AS TOTALCOUNT,
	SUM(TOTAL_REVENUE) AS TOTALREV,
	SUM(TOTAL_REVENUE) / (
		SELECT
			SUM(TOTAL_REVENUE)
		FROM
			STG_CHURN
	) * 100 AS REVPERCENTAGE
FROM
	STG_CHURN
GROUP BY
	CUSTOMER_STATUS;


SELECT
	STATE,
	COUNT(STATE) AS TOTALCOUNT,
	ROUND(
		COUNT(STATE) * 1.0 / (
			SELECT
				COUNT(*)
			FROM
				STG_CHURN
		),
		2
	) AS PERCENTAGE
FROM
	STG_CHURN
GROUP BY
	STATE
ORDER BY
	PERCENTAGE DESC;


SELECT DISTINCT
	INTERNET_TYPE
FROM
	STG_CHURN


--Data Exploration – Check Nulls

SELECT
	SUM(
		CASE
			WHEN CUSTOMER_ID IS NULL THEN 1
			ELSE 0
		END
	) AS CUSTOMER_ID_NULL_COUNT,
	SUM(
		CASE
			WHEN GENDER IS NULL THEN 1
			ELSE 0
		END
	) AS GENDER_NULL_COUNT,
	SUM(
		CASE
			WHEN AGE IS NULL THEN 1
			ELSE 0
		END
	) AS AGE_NULL_COUNT,
	SUM(
		CASE
			WHEN MARRIED IS NULL THEN 1
			ELSE 0
		END
	) AS MARRIED_NULL_COUNT,
	SUM(
		CASE
			WHEN STATE IS NULL THEN 1
			ELSE 0
		END
	) AS STATE_NULL_COUNT,
	SUM(
		CASE
			WHEN NUMBER_OF_REFERRALS IS NULL THEN 1
			ELSE 0
		END
	) AS NUMBER_OF_REFERRALS_NULL_COUNT,
	SUM(
		CASE
			WHEN TENURE_IN_MONTHS IS NULL THEN 1
			ELSE 0
		END
	) AS TENURE_IN_MONTHS_NULL_COUNT,
	SUM(
		CASE
			WHEN VALUE_DEAL IS NULL THEN 1
			ELSE 0
		END
	) AS VALUE_DEAL_NULL_COUNT,
	SUM(
		CASE
			WHEN PHONE_SERVICE IS NULL THEN 1
			ELSE 0
		END
	) AS PHONE_SERVICE_NULL_COUNT,
	SUM(
		CASE
			WHEN MULTIPLE_LINES IS NULL THEN 1
			ELSE 0
		END
	) AS MULTIPLE_LINES_NULL_COUNT,
	SUM(
		CASE
			WHEN INTERNET_SERVICE IS NULL THEN 1
			ELSE 0
		END
	) AS INTERNET_SERVICE_NULL_COUNT,
	SUM(
		CASE
			WHEN INTERNET_TYPE IS NULL THEN 1
			ELSE 0
		END
	) AS INTERNET_TYPE_NULL_COUNT,
	SUM(
		CASE
			WHEN ONLINE_SECURITY IS NULL THEN 1
			ELSE 0
		END
	) AS ONLINE_SECURITY_NULL_COUNT,
	SUM(
		CASE
			WHEN ONLINE_BACKUP IS NULL THEN 1
			ELSE 0
		END
	) AS ONLINE_BACKUP_NULL_COUNT,
	SUM(
		CASE
			WHEN DEVICE_PROTECTION_PLAN IS NULL THEN 1
			ELSE 0
		END
	) AS DEVICE_PROTECTION_PLAN_NULL_COUNT,
	SUM(
		CASE
			WHEN PREMIUM_SUPPORT IS NULL THEN 1
			ELSE 0
		END
	) AS PREMIUM_SUPPORT_NULL_COUNT,
	SUM(
		CASE
			WHEN STREAMING_TV IS NULL THEN 1
			ELSE 0
		END
	) AS STREAMING_TV_NULL_COUNT,
	SUM(
		CASE
			WHEN STREAMING_MOVIES IS NULL THEN 1
			ELSE 0
		END
	) AS STREAMING_MOVIES_NULL_COUNT,
	SUM(
		CASE
			WHEN STREAMING_MUSIC IS NULL THEN 1
			ELSE 0
		END
	) AS STREAMING_MUSIC_NULL_COUNT,
	SUM(
		CASE
			WHEN UNLIMITED_DATA IS NULL THEN 1
			ELSE 0
		END
	) AS UNLIMITED_DATA_NULL_COUNT,
	SUM(
		CASE
			WHEN CONTRACT IS NULL THEN 1
			ELSE 0
		END
	) AS CONTRACT_NULL_COUNT,
	SUM(
		CASE
			WHEN PAPERLESS_BILLING IS NULL THEN 1
			ELSE 0
		END
	) AS PAPERLESS_BILLING_NULL_COUNT,
	SUM(
		CASE
			WHEN PAYMENT_METHOD IS NULL THEN 1
			ELSE 0
		END
	) AS PAYMENT_METHOD_NULL_COUNT,
	SUM(
		CASE
			WHEN MONTHLY_CHARGE IS NULL THEN 1
			ELSE 0
		END
	) AS MONTHLY_CHARGE_NULL_COUNT,
	SUM(
		CASE
			WHEN TOTAL_CHARGES IS NULL THEN 1
			ELSE 0
		END
	) AS TOTAL_CHARGES_NULL_COUNT,
	SUM(
		CASE
			WHEN TOTAL_REFUNDS IS NULL THEN 1
			ELSE 0
		END
	) AS TOTAL_REFUNDS_NULL_COUNT,
	SUM(
		CASE
			WHEN TOTAL_EXTRA_DATA_CHARGES IS NULL THEN 1
			ELSE 0
		END
	) AS TOTAL_EXTRA_DATA_CHARGES_NULL_COUNT,
	SUM(
		CASE
			WHEN TOTAL_LONG_DISTANCE_CHARGES IS NULL THEN 1
			ELSE 0
		END
	) AS TOTAL_LONG_DISTANCE_CHARGES_NULL_COUNT,
	SUM(
		CASE
			WHEN TOTAL_REVENUE IS NULL THEN 1
			ELSE 0
		END
	) AS TOTAL_REVENUE_NULL_COUNT,
	SUM(
		CASE
			WHEN CUSTOMER_STATUS IS NULL THEN 1
			ELSE 0
		END
	) AS CUSTOMER_STATUS_NULL_COUNT,
	SUM(
		CASE
			WHEN CHURN_CATEGORY IS NULL THEN 1
			ELSE 0
		END
	) AS CHURN_CATEGORY_NULL_COUNT,
	SUM(
		CASE
			WHEN CHURN_REASON IS NULL THEN 1
			ELSE 0
		END
	) AS CHURN_REASON_NULL_COUNT
FROM
	STG_CHURN;

--Remove null and insert the new data into Prod table

CREATE TABLE PROD_CHURN AS
SELECT
	CUSTOMER_ID,
	GENDER,
	AGE,
	MARRIED,
	STATE,
	NUMBER_OF_REFERRALS,
	TENURE_IN_MONTHS,
	COALESCE(VALUE_DEAL, 'None') AS VALUE_DEAL,
	PHONE_SERVICE,
	COALESCE(MULTIPLE_LINES, 'No') AS MULTIPLE_LINES,
	INTERNET_SERVICE,
	COALESCE(INTERNET_TYPE, 'None') AS INTERNET_TYPE,
	COALESCE(ONLINE_SECURITY, 'No') AS ONLINE_SECURITY,
	COALESCE(ONLINE_BACKUP, 'No') AS ONLINE_BACKUP,
	COALESCE(DEVICE_PROTECTION_PLAN, 'No') AS DEVICE_PROTECTION_PLAN,
	COALESCE(PREMIUM_SUPPORT, 'No') AS PREMIUM_SUPPORT,
	COALESCE(STREAMING_TV, 'No') AS STREAMING_TV,
	COALESCE(STREAMING_MOVIES, 'No') AS STREAMING_MOVIES,
	COALESCE(STREAMING_MUSIC, 'No') AS STREAMING_MUSIC,
	COALESCE(UNLIMITED_DATA, 'No') AS UNLIMITED_DATA,
	CONTRACT,
	PAPERLESS_BILLING,
	PAYMENT_METHOD,
	MONTHLY_CHARGE,
	TOTAL_CHARGES,
	TOTAL_REFUNDS,
	TOTAL_EXTRA_DATA_CHARGES,
	TOTAL_LONG_DISTANCE_CHARGES,
	TOTAL_REVENUE,
	CUSTOMER_STATUS,
	COALESCE(CHURN_CATEGORY, 'Others') AS CHURN_CATEGORY,
	COALESCE(CHURN_REASON, 'Others') AS CHURN_REASON
FROM
	STG_CHURN;

SELECT
	*
FROM
	PROD_CHURN;

--Create View for Power BI
CREATE VIEW VW_CHURNDATA AS
SELECT
	*
FROM
	PROD_CHURN
WHERE
	CUSTOMER_STATUS IN ('Churned', 'Stayed');

CREATE VIEW VW_JOINDATA AS
SELECT
	*
FROM
	PROD_CHURN
WHERE
	CUSTOMER_STATUS = 'Joined';


\copy prod_churn TO 'C:\Users\vc\Desktop\NIHARIKA\Complete churn Data & Resources\prod_churn.csv' CSV HEADER;